version: "3"

services:
  api-dummy-d:
    image: "${IMAGE_PREFIX}api-dummy-d-image:${IMAGE_TAG:-latest}"
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./global.d.ts:/code/global.d.ts
      - ./server.ts:/code/server.ts
      - ./tsconfig.json:/code/tsconfig.json
      - ./src:/code/src/
    ports:
      - "8080:8000"
    # networks:
    #   - some-external-network
    working_dir: /code
    entrypoint: /bin/sh
    command: '-c "npx tsc-watch --preserveWatchOutput --compiler /code/node_modules/.bin/ttsc --onSuccess "/sbin/docker-entrypoint.sh prod""'

# networks:
#   some-external-network:
#     external:
#       name: some-external-network
